### ISSUE TITLE
Show unread messages count on ZeroHello?

### ISSUE THREAD

**Issue by makdisse** [HelloZeroNet/ZeroMail#11]
How can we make it visible that there are new emails on the zero hello so that the user knows he needs to open zeromail to check his emails?
From my tests, if you receive an email, you just learn about it if you open the zeromail app

**Comment by HelloZeroNet** [comment]
The decryption is done by the site, so it's not possible unfortunately.

**Comment by slrslr** [comment]
Hello, there is a bot that seem to show new e-mails in ZeroHello newsfeed:
http://127.0.0.1:43110/1EiMAqhd6sMjPG2tznkkGXxhdwFBDdeqT9/?Post:67
