### ISSUE TITLE
Hide the sender

### ISSUE THREAD

**Issue by weakish** [HelloZeroNet/ZeroMail#13]
Currently the sender of message is not hidden
(encrypt then sign, not sign then encrypt).

Analyse senders of messages and timestamps,
we can recognize receiver for a lot of messages
(Most messages are conversation between users,
and most users reply messages within a certain period.)

Maybe ZeroMail can use a different architeture than ZeroTalk/ZeroBlog etc.
The sender sign and encrypt, and transfer the encrypted message to site owner.
The site owner then publish the encrypted message (may require sender to do some POW).
Only the receiver can decrypt the message, and after decryption they see the sender address/id and signature.

Sent and received mails as well as contacts are stored in browser storage locally.
They can be exported and imported manually by user.

To reduce disk space usage, old mails are archived in optional files periodically.

**Comment by HelloZeroNet** [comment]
This is exactly what bitmessage is: https://bitmessage.org/wiki/Main_Page

I don't think a case-specific, alternative protocol would be a good idea, but a zeronet plugin for bitmessage could be possible. (communicate locally running bitmessage client via xmlrpc)
