### ISSUE TITLE
OpenSSL: error message using newer lib >= 1.1

### ISSUE THREAD

**Issue by haschimoto** [HelloZeroNet/ZeroMail#17]
/usr/lib/arm-linux-gnueabihf/libssl.so.1.1: undefined symbol: ECDH_OpenSSL
![snap 2017-03-01 at 15 36 20](https://cloud.githubusercontent.com/assets/20817185/23464366/0ad5fa62-fe95-11e6-8c06-3c9261ad8910.png)

Same issue likely as here:
https://github.com/nfcpy/nfcpy/issues/59

**Comment by HelloZeroNet** [comment]
Probably they renamed or changed the function we need. It would be nice if someone with experience in c++ programming could fix the dll calls: https://github.com/HelloZeroNet/ZeroNet/blob/master/src/lib/opensslVerify/opensslVerify.py

**Comment by haschimoto** [comment]
it seems this also affects general useage?:
![snap 2017-03-07 at 16 59 43](https://cloud.githubusercontent.com/assets/20817185/23665022/9526dab2-0357-11e7-9076-e44fa311b896.png)

**Comment by HelloZeroNet** [comment]
Yeah, using the pure-python crypto lib is using around 50x more cpu time.

**Comment by haschimoto** [comment]
It seems I cannot publish anything anymore though. 
When publishing, it now always reports 0 peers found, even though on big sites which lists hundreds of peers like Talk, etc.
I can still refresh sites though, so I am still connected.
This SSL is imo a big issue affecting the complete useage of Zeronet (latest client 0.5.3 v1993) and newer SSL, which is common now like under Debian, Ubuntu, etc.

**Comment by HelloZeroNet** [comment]
There is a package for linux that also include openssl: https://github.com/HelloZeroNet/ZeroBundle/raw/master/dist/ZeroBundle-linux64.tar.gz

**Comment by haschimoto** [comment]
@HelloZeroNet : 
Bump: A general fix would be welcome.
Anyone who doesnt use the bundle but set zeronet up manually (as in your own tutorial) is basically cut out from using communication tools like zeromail.

**Comment by HelloZeroNet** [comment]
As far as I know none of most of linux distributions still using openssl 1.0.x, but it's definitely planned in the future.

**Comment by haschimoto** [comment]
You meant "none" or "most" still use 1.0.x?

**Comment by haschimoto** [comment]
Debian testing/stretch/sid all started using 1.1.x:
https://packages.debian.org/de/stretch/openssl

**Comment by HelloZeroNet** [comment]
Can you please specify your operating system, so I can try to reproduce it?

**Comment by haschimoto** [comment]
I use Netrunner Core, but ARMHF-version for microcomputer (so current 32/64bit Linux-bundles of Zeronet are not an option for this hardware).

There is a 64bit of Netrunner Core though to possibly test the error when manually installing zeronet on it:
https://sourceforge.net/projects/netrunneros/files/netrunner-1701-core/netrunner-core-1701-64bit.iso/download

**Comment by HelloZeroNet** [comment]
It should be fixed in latest version:
https://github.com/HelloZeroNet/ZeroNet/commit/86506515675ffa6d5e6d9080d6e836597c749ac2
Please update and try again.

**Comment by haschimoto** [comment]
works again flawlessly, thank you very much!
