### ISSUE TITLE
Inbox doesn't work

### ISSUE THREAD

**Issue by charlierunkle64** [HelloZeroNet/ZeroMail#29]
I don't get messages to my inbox, 4 file updates are failing. 
Running on MacOS 10.13.1 Tor 7.0.11

thanks for support

charles

PS: the three dots in the 2nd picture are not placed correctly (as you can see ;-)

![pic2](https://user-images.githubusercontent.com/34578912/34049998-9b5afff8-e1b9-11e7-9267-2c0ed639db1d.png)
![pic1](https://user-images.githubusercontent.com/34578912/34049999-9b9750ca-e1b9-11e7-85a2-ee4b56edb73c.png)

**Comment by HelloZeroNet** [comment]
Do you have any error in your javascript console? (F12)

**Comment by charlierunkle64** [comment]
Yes, I have
Any help with them?

![screen](https://user-images.githubusercontent.com/34578912/34365096-bffa47ca-ea8c-11e7-9c9b-7b36b51ac3a7.png)

**Comment by HelloZeroNet** [comment]
Looks like your browser is blocking localstorage. Is this works for you: https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_webstorage_local_clickcount

**Comment by charlierunkle64** [comment]
thanks, problem solved
