### ISSUE TITLE
Flood of the errors "verify sign error: VerifyError: Content too large" on ZeroMail

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroMail#36]
Hello,

i installed Zeronet on a new computer and signed in using my old zeroID.
Then opened ZeroMail, where i have been apparently signed in because i seen list of my e-mails from my old computer, it started computing some signatures or something like that on that page, showing percentage progress. Issue is that it took like 15 minutes (i had to kill ZN then because of the overload) when the HDD and CPU was maxed out apparently because of that ZeroMail activity, because i found in ZeroNet debug.log following kind of entries:

> [23:11:45] Site:1MaiL5..Ju27 data/users/13uxje4zHPcMsVRpZXPvzBg7HLnV2YPptS/content.json: verify sign error: VerifyError: Content too large 11188519B > 10485760B, aborting task... in ContentManager.py line 890 > ContentManager.py line 771
> [23:11:45] Site:1MaiL5..Ju27 data/users/17ntZ9ec9AMDMqH9ztNnxkWTKQf2wVsv3P/content.json: verify sign error: VerifyError: Content too large 11187793B > 10485760B, aborting task... in ContentManager.py line 890 > ContentManager.py line 771
> [23:11:45] Site:1MaiL5..Ju27 data/users/1DqfgsZuTkzYTur4cEmZgNrrarNFRz6di2/content.json: verify sign error: VerifyError: Content too large 11187575B > 10485760B, aborting task... in ContentManager.py line 890 > ContentManager.py line 771

(several entries per second, total around 25 thousand of entries containing phrase "10485760B, aborting task...")

I know i probably reached my limit, but i think users should not face this issue when reaching the limit
I had to kill zeronet.py on my Linux Ubuntu 16.04, ZeroNet 0.6.3 r3597, Python 2.7.11 in order to stop the PC overload. After start it starts again.

**Comment by HelloZeroNet** [comment]
Probably it should abort the download process if it almost reached of site size limit.

**Comment by HelloZeroNet** [comment]
I have added a change that will stop the download process if 95% of the site limit is reached: https://github.com/HelloZeroNet/ZeroNet/commit/9658c2d5530bd543aca819b00e778bdc464235f0
