### ISSUE TITLE
Raise the limit

### ISSUE THREAD

**Issue by rllola** [HelloZeroNet/ZeroMail#38]
Is it possible to raise the limit to 1mb ? See https://github.com/HelloZeroNet/ZeroNet/issues/1671

**Comment by HelloZeroNet** [comment]
I think it would be problematic to store that amount of data for every users, so I recommend to delete older emails. You can press shift to select multiple items in your sent folder.

**Comment by DaniellMesquita** [comment]
ZeroMail should work with hubs.
And a hub called "New messages", where new messages appears and are transfered to other hub after some days.

**Comment by rllola** [comment]
> 
> 
> I think it would be problematic to store that amount of data for every users, so I recommend to delete older emails. You can press shift to select multiple items in your sent folder.

Yeah I forgot that there is all the mails from everyone so it would easily escalate... An interesting feature would be to automatically archive it when the person read it... So they could keep it localy.
