### ISSUE TITLE
ZeroMail doesn't work because of AttributeError

### ISSUE THREAD

**Issue by filips123** [HelloZeroNet/ZeroMail#42]
I can't use ZeroMail because of `Attribute` error which occurs when I open ZeroMail, try to load messages or try to send message:

```
Internal error: AttributeError: '_OpenSSL' object has no attribute 'digest_ecdsa_sha1'

  UiWebsocket.py line 85 >
  UiWebsocket.py line 234 >
  CryptMessage/CryptMessagePlugin.py line 86 >
  __init__.py line 17 >
  ecc.py line 20 >
  ecc.py line 323
```

I'm using Python 3 ZeroBundle with revision 4167.

@HelloZeroNet Also, can you raise my ZeroTalk limit for `filips@zeroid.bit`? I can't contact yu with ZeroMail because of this error.

**Comment by HelloZeroNet** [comment]
Thanks fore reporting fixed in Rev4169:
https://github.com/HelloZeroNet/ZeroNet/commit/cc21cbd1bd9411d602eb9a440889082e4c73b921
https://github.com/HelloZeroNet/ZeroNet/commit/1cfe8748937b3d3a1d6fe9da354a835351c19e27
