### ISSUE TITLE
Ubuntu 19.04 + ZeroNet 0.7.1 rev4210

### ISSUE THREAD

**Issue by katian** [HelloZeroNet/ZeroMail#43]
Hello,
I have this error on ZeroMail :
![ZeroMail_issue](https://user-images.githubusercontent.com/1428843/64907411-78e1bb80-d6f2-11e9-8cb2-d31a615e29c7.png)

snap info :
```
channels:
  stable:    0.7.1-r4210 2019-09-12 (2115) 21MB -
  candidate: 0.7.1-r4210 2019-09-12 (2115) 21MB -
  beta:      0.7.1-r4210 2019-09-12 (2115) 21MB -
  edge:      0.7.1-r4210 2019-09-12 (2115) 21MB -
installed:   0.7.1-r4210            (2115) 21MB -

```
Thanks

**Comment by blurHY** [comment]
Consider upgrading your openssl stuff

**Comment by imachug** [comment]
@HelloZeroNet Didn't I fix that already?

**Comment by HelloZeroNet** [comment]
Fixed by https://github.com/ZeroNerds/zeronet-snap/issues/8
