### ISSUE TITLE
translation is not done correctly in brazilian portuguese

### ISSUE THREAD

**Issue by eduardoaddad** [HelloZeroNet/ZeroMail#47]
translation is not done correctly in brazilian portuguese

![Captura de Tela (13)](https://user-images.githubusercontent.com/16819380/71629857-8c9c2980-2bde-11ea-815b-efad5e274713.png)

**Comment by eduardoaddad** [comment]
@HelloZeroNet will the correction be made?

**Comment by HelloZeroNet** [comment]
Thanks for reporting, it should be fine now
