### ISSUE TITLE
Add a new email address

### ISSUE THREAD

**Issue by ripper234** [HelloZeroNet/ZeroMail#5]
I'm [trying](http://talk.zeronetwork.bit/?Topic:10_1MxdAjWgnqwCaunGHmhY39tVR51qV3peJL/ZeroMail+support+thread) to create a second email address, and I haven't figured out if it's possible to do this right now.

Ideally, this should be a simple button "switch/create a new email address with this ID".
Another solution could be to create a new ID, but I haven't [found out how](https://github.com/HelloZeroNet/ZeroID/issues/1) to do that yet.

**Comment by HelloZeroNet** [comment]
You can enable Multiuser plugin by renaming plugins/disabled-Multiuser to plugins/Multiuser, this adds cookie based identity mangement. But this way you have to take care to store your private keys (displayed on first visit), because it's not written on hdd

**Comment by ripper234** [comment]
How do I locate/store my private keys?
Do I just need to back them up once? Or every identity I add?

**Comment by HelloZeroNet** [comment]
One identity = one master_seed

**Comment by veaceslavdoina** [comment]
@HelloZeroNet, how can I start ZeroNet in mode when it does not create new identity at startup?
It should only provide possibility to "Login with existing identity" or "Create new identity".

Thank you!

**Comment by HelloZeroNet** [comment]
In Multiuser mode you can logout from your current account using ZeroHello

**Comment by veaceslavdoina** [comment]
It works, thank you!

And can I start it in mode without creating a new identity?

If I have only some permanent identity I will only use "Login" and "Switch" funtion. It this case I do not need every start new identity creation.

Thank you!

**Comment by veaceslavdoina** [comment]
Also how can I switch one identity to another in users.json ?
I have only "auth_privatekey" = master_seed, you mentioned.
How can I find: "auth_address", "cert_sign" ?

As I understand "auth_user_name" is created during Certificate creation on ZeroID site and I know it.

**Comment by HelloZeroNet** [comment]
It's added to users.json automatically when you visit the zeroid site

**Comment by veaceslavdoina** [comment]
Verified now:
1. Renamed plugins/disabled-Multiuser --> plugins/Multiuser.
2. Started ZeroNET.
3. Verified changes in user - it remained same as in single user mode.

Thank you!

**Comment by lezsakdomi** [comment]
Don't forget to state explicitly that this is a local machine, when enabling the multiuser plugin just for this purpose.
```bash
./zeronet.py --multiuser_local
```
