### ISSUE TITLE
Support a mailto equivalent link

### ISSUE THREAD

**Issue by Codes4Fun** [HelloZeroNet/ZeroMail#7]
I already see people say "Send me a ZeroMail" but then you have to manually enter their email address and copy and paste it.

I am thinking of something like this: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_mailto

I would think it would work like this:
`<a href="http://127.0.0.1:43110/Mail.ZeroNetwork.bit/#mailto:soandso@zeroid.bit&Subject=Hello%20World">Say hello to soandso</a>`

And then on ZeroMail page load do all the string magic to location.hash to extract it.

**Comment by HelloZeroNet** [comment]
there is: http://127.0.0.1:43110/Mail.ZeroNetwork.bit/?to=nofish
